; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8_128k]
platform = ststm32
board = bluepill_f103c8_128k
framework = arduino
lib_deps = fastled/FastLED @ ^3.6.0


; --- SERIAL UPLOAD SETTINGS ---
upload_protocol = serial
; If you know your COM port (e.g., COM3 or /dev/ttyUSB0), uncomment below:
; upload_port = COM3